/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LAC */

#ifndef _Included_lacjni
#define _Included_lacjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LAC
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_nlp_LAC_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LAC
 * Method:    loadCustomization
 * Signature: (Ljava/lang/String;)Jint
 */
JNIEXPORT jint JNICALL Java_com_baidu_nlp_LAC_loadCustomization
  (JNIEnv *, jobject, jstring);



/*
 * Class:     LAC
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String[];Ljava/lang/String[])Jint
 */
JNIEXPORT jint JNICALL Java_com_baidu_nlp_LAC_run
  (JNIEnv *, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
